spring.application.name=fridgecalories
spring.datasource.url=jdbc:mysql://localhost:3306/fridgeCalories
spring.datasource.username=PabloAdmin
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true